# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/KMUTT/FIBO/year 3/1/MBED/FPGA/PWM_LED2/PWM_LED2.srcs/sources_1/bd/MicroZED/ip/MicroZED_processing_system7_0_0/MicroZED_processing_system7_0_0.xci
# IP: The module: 'MicroZED_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/KMUTT/FIBO/year 3/1/MBED/FPGA/PWM_LED2/PWM_LED2.gen/sources_1/bd/MicroZED/ip/MicroZED_processing_system7_0_0/MicroZED_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroZED_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/KMUTT/FIBO/year 3/1/MBED/FPGA/PWM_LED2/PWM_LED2.srcs/sources_1/bd/MicroZED/ip/MicroZED_processing_system7_0_0/MicroZED_processing_system7_0_0.xci
# IP: The module: 'MicroZED_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/KMUTT/FIBO/year 3/1/MBED/FPGA/PWM_LED2/PWM_LED2.gen/sources_1/bd/MicroZED/ip/MicroZED_processing_system7_0_0/MicroZED_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroZED_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
