# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MicroZED_ledPWM.xdc

# Block Designs: bd/MicroZED/MicroZED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroZED || ORIG_REF_NAME==MicroZED} -quiet] -quiet

# IP: bd/MicroZED/ip/MicroZED_processing_system7_0_0/MicroZED_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroZED_processing_system7_0_0 || ORIG_REF_NAME==MicroZED_processing_system7_0_0} -quiet] -quiet

# IP: bd/MicroZED/ip/MicroZED_pwmLED_0_0/MicroZED_pwmLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MicroZED_pwmLED_0_0 || ORIG_REF_NAME==MicroZED_pwmLED_0_0} -quiet] -quiet

# XDC: d:/KMUTT/FIBO/year 3/1/MBED/FPGA/PWM_LED2/PWM_LED2.gen/sources_1/bd/MicroZED/MicroZED_ooc.xdc
